# Generated by Django 2.1.5 on 2020-03-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumiao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='appgender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='usergender',
            field=models.BooleanField(default=False),
        ),
    ]
