# Generated by Django 2.1.5 on 2020-03-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumiao', '0002_auto_20200319_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='adminauthority',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admintelephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='appage',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='appincome',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cat',
            name='catage',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertelephone',
            field=models.CharField(max_length=20),
        ),
    ]
