# Generated by Django 2.1.5 on 2020-03-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumiao', '0003_auto_20200319_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='appemail',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='admin',
            name='adminid',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='appgender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='appid',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='cat',
            name='catid',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='usergender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
