# Generated by Django 2.1.5 on 2020-03-27 11:04

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('yumiao', '0004_auto_20200326_2133'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cat',
            managers=[
                ('catObj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='cat',
            name='catpicture',
            field=models.ImageField(default=False, upload_to='img'),
        ),
    ]
