# Generated by Django 2.1.5 on 2020-03-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumiao', '0005_auto_20200327_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='apppicture',
            field=models.ImageField(default=False, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='catpicture',
            field=models.ImageField(default=False, upload_to='upload/'),
        ),
    ]
